version: '3'

services:
  ada-note:
    environment:
      - AUTH_SECRET="MohY0/2zSQw/psWEnejC2ka3Al0oifvY4YjOkUaFfnI="
      - AUTH_URL=http://localhost:3000
    build:
      context: .
      dockerfile: Dockerfile
    image: lileepy/ada-note
    ports:
      - '3000:3000'
